---
title: "integrity checking"
output: html_document
date: "2025-02-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
#check empty
```{r}
#input format: dataframe need to be checked
#output format: 2 col dataframe. 
#   col features: name of the columns; 
#   col percent: percentage of missing of the columns
check_na=function(df){
  #initialize 
  percent=c()
  
  idxs=df[1,]
  
  for(col in 1:ncol(df)){
    
    na_count=sum(is.na(df[,col]))
    percent=c(percent,na_count/nrow(df))
  }
  
  result=data.frame(features=names(df),percent=percent)
  return(result)
}




#simulation
X=rnorm(500*50,0,1)
X[which(X<0)]=NA
d=data.frame(matrix(X,nrow=500,ncol=50))
check_na(d)
```

#check constant
```{r} 
#input format: dataframe need to be checked
#output format: 2 col dataframe. 
#   col features: name of the columns; 
#   col is_constant: whether this column is constant(1 is constant; 0 is non-constant)
is_constant=function(d,thresh){
  d=na.omit(d)
  if(class(d)!="numeric"){
    unq_list=unique(d)
    if(length(unq_list)<=1)
      return(TRUE)
    else
      return(FALSE)
  }
  
  else{
    low_bound=min(d)
    up_bound=max(d)
    if(abs(low_bound-up_bound)<thresh)
      return(TRUE)
    else
      return(FALSE)
  }

}
check_constant=function(df,thresh=0.00001){
  #initialize
  constant_sign=c()
  col_list=names(df)
  #check each column
  for(i in 1:ncol(df)){
    if(is_constant(df[,i],thresh))
      constant_sign=c(constant_sign,1)
    else
      constant_sign=c(constant_sign,0)
  }
  result=data.frame(features=names(df),is_constant=constant_sign)
  return(result)
}

#simulation
X=rnorm(500*50,0,1)
d=data.frame(matrix(X,nrow=500,ncol=50))
const_col=sample(1:50,7)
d[,const_col]=0.0000000000001
sort(which(check_constant(d)$is_constant==1),decreasing=FALSE)
sort(const_col,decreasing=FALSE)
```
#check datatype
```{r}
get_datatype=function(col){
  col=na.omit(col)
  if (length(col) == 0) {
    detected_type <- "Empty"
  } else if (all(is.numeric(col))) {
    if (all(col %in% c(0, 1))) {
      detected_type <- "Binary"
    } else {
      detected_type <- "Numeric"
    }
  } else if (any(grepl("^\\d{4}-\\d{2}-\\d{2}$", col))) {
    detected_type <- "Date"
  } else {
    detected_type <- "Categorical"
  return(detected_type)
  }
}
  
check_datatype=function(df){
  data_type=c()
  #check each column
  for(i in 1:ncol(df)){
    data_type=c(data_type,get_datatype(df[,i]))
  }
  result=data.frame(features=names(df),type=data_type)
  return(result)
}
```

```{r}
get_most_frequent=function(s){
  freq_table=table(s)
  most_frequent=names(which.max(freq_table))
  return(most_frequent)
}
```


#function: get meta data
```{r}
library(dplyr)
number_file=100
get_meta=function(path=".",number_file){
  #initialize
  features=c()#record columns with low missing
  missing_percent=c()
  #record their missing percent
  subsample_idx=c()#record the subsample they belong to
  constant=c()
  types=c()

  #go through each subsample csv
  for(i in 1:number_file){
    df=read.csv(paste0(path,"/subsampled_",i,".csv"))
    #get missing percent in current subsample using previous method
    na_info=check_na(df)
    constant_info=check_constant(df)
    type_info=check_datatype(df)
    #update result
    features=c(features,na_info$features)
    constant=c(constant,constant_info$is_constant)
    missing_percent=c(missing_percent,na_info$percent)
    types=c(types,type_info$type)
    idx=rep(i,ncol(df))
  
    subsample_idx=c(subsample_idx,idx)
  }

  meta_data=data.frame(features=features,missing_percent=missing_percent,is_constant=constant,subsample_index=subsample_idx,type=types)
  unique_meta_data=meta_data%>% group_by(features) %>%summarise(missing_percent=mean(missing_percent),is_constant=round(mean(is_constant)),types=get_most_frequent(type))
  return(unique_meta_data)
}

```
#get meta data
```{r}
meta_data=data.frame(get_meta(path="./UKBB subsamples/2000x500r_50c/subsamples",number_file=2000))
write.csv(meta_data,"meta_data_Mar20.csv")
```


#get all columns from subsamples
```{r eval=FALSE, include=FALSE}
all_columns=c()
for(i in 1:number_file){
  df=read.csv(paste0("subsampledData_",i,".csv"))
  columns=names(df)
  all_columns=c(all_columns,columns)
}
all_columns=unique(all_columns)
usable_features_percent=length(usable_features)/length(all_columns)
usable_features_percent
```

#get data type
```{r eval=FALSE, include=FALSE}
data_type=c()
for(i in 1:ncol(low_missing_df)){
  data_type=c(data_type,class(low_missing_df[,i]))
}
```


#construct low-missing dataframe
```{r eval=FALSE, include=FALSE}

#result from previous step, recording low-missing columns and their subset
low_missing_features=low_missing_result

#initialize
low_missing_df=matrix(NA,nrow=500)
low_missing_df=data.frame(low_missing_df)
names_df=c()

#go through each subsample
for(i in low_missing_features$subsample_idx){
  
  df=read.csv(paste0("subsampledData_",i,".csv"))
  
  #select information about missing for subsample i
  df_temp=low_missing_features[low_missing_features$subsample_idx==i,]
  
  #go through each low-missing column in subsample i
  for(f in df_temp$features){
    
    #get colname
    names_feature=paste0(f,"_subsample_",i)
    names_df=c(names_df,names_feature)
    
    #add the low-missing column in the objective dataframe
    low_missing_df=cbind(low_missing_df,df[,f])
  }
}

low_missing_df=low_missing_df[,-1]

#set column names
names(low_missing_df)=names_df

#save result
write.csv(low_missing_df,"low_missing_data.csv")
```

```{r}
df=read.csv("subsampled_1374.csv")
check_datatype(df)
```

